### ISSUE TITLE
Managed Identity: Configurable timeout based on time

### ISSUE THREAD

**Issue by arluca** [Azure/msrestazure-for-python#125] opened 2019-01-31 00:08 UTC
Currently, the retry logic in the Azure SDKs for Managed Identity token generation supports a configurable time out based on counts. For response time sensitive services this has not been enough. Per customer feedback, they would like to have timeout configuration based on time (i.e. milliseconds) 
This will allow for quicker fail after certain.
Can we make the retry max configurable based on time?

@binderjoe FYI

**Comment by yugangw-msft** [comment] 2019-02-06 03:55
would it be a python pattern that we offer a cancel callback?

**Comment by arluca** [comment] 2019-02-08 19:51
@yugangw-msft : Was that a question for me or for @lmazuel ?

**Comment by yugangw-msft** [comment] 2019-02-08 20:26
for @lmazuel

**Comment by lmazuel** [comment] 2019-02-08 20:35
@yugangw-msft if I understand your question and implication, you are thinking about providing a callback instead of a timeout parameter, to be more generic and offer more possibility to cancel. Am I correct?

**Comment by yugangw-msft** [comment] 2019-02-08 21:47
@lmazuel, that is correct. It is your call on which one is better.

**Comment by lmazuel** [comment] 2019-02-09 00:22
@arluca that's actually a duplicate of https://github.com/Azure/msrestazure-for-python/issues/99 right?

**Comment by arluca** [comment] 2019-02-09 00:48
Yes. That was the original request.

Arturo Lucatero [LinkedIn<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Farturo-lucatero&data=04%7C01%7C%7C1f19e83c655c43523fb208d61833ec23%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636723008644823124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=RKgUrONgQDBbP4wIa0fUm3K1n%2B5GCYvqn%2FBiZ0eGk0Y%3D&reserved=0> | Twitter<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FArLucaID&data=04%7C01%7C%7C1f19e83c655c43523fb208d61833ec23%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636723008644833136%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=o2%2FWgOKikQzXxhgnEM%2BBhUhScrWpPYkZsj2BvqelJkg%3D&reserved=0>]
Managed Identities for Azure resources docs<http://aka.ms/msidocs> | Onboarding to Azure IAM<https://microsoft.sharepoint.com/teams/AzureMSI/SitePages/Home.aspx> | Azure IAM office hours<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FAzureRBACMSI-OfficeHours&data=04%7C01%7C%7C1f19e83c655c43523fb208d61833ec23%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636723008644843145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=i5udbijTDcf0PE2JGJM6LBiG4D%2Bwcn0V9EqNJB4ZNb0%3D&reserved=0>

**Comment by lmazuel** [comment] 2019-02-09 01:25
And did my suggestion worked?

**Comment by arluca** [comment] 2019-02-12 04:21
My bad. I went through and opened on all SDKs. the suggestion you suggested initially is acceptable. You can close this as duplicate.

**Closed** 2019-02-27 17:56 UTC
Labels: enhancement
