### ISSUE TITLE
Cannot install 'azure' on windows CPython 3.6 (64-bit)

### ISSUE THREAD

**Issue by huguesv** [Azure/msrestazure-for-python#25] opened 2017-05-25 22:48 UTC
```
Collecting pywin32-ctypes; sys_platform == "win32" (from keyring>=5.6->msrestazure~=0.4.7->azure-batch~=3.0.0->azure)
  Downloading pywin32-ctypes-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\huvalo\AppData\Local\Temp\pip-build-7w4q35bl\pywin32-ctypes\setup.py", line 7, in <module>
        os.path.join(HERE, 'VERSION')).read().strip()
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\huvalo\\AppData\\Local\\Temp\\pip-build-7w4q35bl\\pywin32-ctypes\\VERSION'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\huvalo\AppData\Local\Temp\pip-build-7w4q35bl\pywin32-ctypes\
----- Failed to install 'azure' -----
```

Manually installing `keyring==5.6` works.

**Comment by lmazuel** [comment] 2017-05-26 00:06
Caused by https://github.com/enthought/pywin32-ctypes/issues/60

**Comment by lmazuel** [comment] 2017-05-30 21:30
Fixed by new release of pywin32

**Closed by lmazuel** 2017-05-30 21:30 UTC
