### ISSUE TITLE
HTTPError raised by MSIAuthentication doesn't contain the error message

### ISSUE THREAD

**Issue by jiasli** [Azure/msrestazure-for-python#153] opened 2020-07-31 09:02 UTC
To repro:

```py
from msrestazure.azure_active_directory import MSIAuthentication
from requests import HTTPError

try:
    auth = MSIAuthentication(resource="https://management.azure.com")
except HTTPError as ex:
    print(ex.response.data)
```

Output:

```
b''
```

When `HTTPError` occurs (no managed identity configured), the exception doesn't contain the error message, which should be 

```
{"error":"invalid_request","error_description":"Identity not found"}
```

This is because `result.raw` has been consumed by `requests` and `result.raw.data` returns an empty `bytes`.

https://github.com/Azure/msrestazure-for-python/blob/7986cdcc41d4131e1d6d866e8c80925921e25969/msrestazure/azure_active_directory.py#L703-L704

![image](https://user-images.githubusercontent.com/4003950/89018288-35b22a80-d34e-11ea-806e-a36eb56374db.png)

### Solution

The `HTTPError` should contain the response `result` from `requests.get` rather than the consumed `result.raw`, so that the error message can be retrieved.

```py
 elif result.status_code != 200: 
     raise HTTPError(request=result.request, response=result) 
```

![image](https://user-images.githubusercontent.com/4003950/89018674-cb4dba00-d34e-11ea-81f4-fab1858bb2ed.png)

**Comment by lmazuel** [comment] 2020-07-31 16:53
Seems a duplicate of https://github.com/Azure/msrestazure-for-python/issues/134?

**Comment by lmazuel** [comment] 2020-12-30 20:06
Closing, since the recommended approach now is officially to use azure-identity to pull MSI token

**Closed by lmazuel** 2020-12-30 20:06 UTC
